name: Deploy readme.txt to WordPress.org

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            readme.txt
          sparse-checkout-cone-mode: false

      - name: Test
        run: |
          echo ${{ secrets.SVN_USERNAME }}
