name: Deploy readme.txt to WordPress.org

on:
  workflow_dispatch:
    inputs:
      svn_path:
        description: 'Subversion path (default: trunk)'
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github
            readme.txt

      - name: Deploy
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PATH: ${{ inputs.svn_path }} 
          WP_SLUG: pronamic-pay-with-mollie-for-woocommerce
        run: php .github/scripts/deploy-readme-to-wordpress-org.php
